version: 0.1

phases:
  install:
    commands:
      - echo "Nothing to do in the installation phase."
  pre_build:
    commands:
      - |
        mkdir -p /tmp/artifacts
  build:
    commands:
      - |
        timestamp=$(date +%Y%m%d%H%M)
        echo "{\"timestamp\":\"${timestamp}\",\"sourceBucket\":\"${TEMPLATE_BUCKET}\",\"pipelineName\":\"${PIPELINE_NAME}\",\"GitHubOwner\":\"${GitHubOwner}\",\"GitHubRepo\":\"${GitHubRepo}\",\"GitHubBranch\":\"${GitHubBranch}\",\"GitHubToken\":\"${GitHubToken}\"}" > /tmp/artifacts/parameters.json
        for this_lambda in $(ls "${CODEBUILD_SRC_DIR}/Lambdas"); do
          cd ${CODEBUILD_SRC_DIR}/Lambdas/${this_lambda}
          zip -r "/tmp/artifacts/${this_lambda}.zip" *
          aws s3 cp \
            "/tmp/artifacts/${this_lambda}.zip" \
            "s3://${TEMPLATE_BUCKET}/${PIPELINE_NAME}/artifacts/${timestamp}/" \
            --sse aws:kms \
            --sse-kms-key-id "${KMS_ARN}"
        done
  post_build:
    commands:
      - echo "Nothing to do in the post-build phase."
artifacts:
  files:
    - /tmp/artifacts/parameters.json
  discard-paths: yes